# Generated by Django 5.2.4 on 2025-10-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervencao',
            old_name='titulo',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
