# Generated by Django 5.2.4 on 2025-10-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencoes', '0002_rename_titulo_intervencao_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencao',
            name='categoria',
            field=models.CharField(choices=[('MOBILIÁRIO URBANO', 'MOBILIÁRIO URBANO'), ('ESPAÇOS LIVRES DE ESTAR', 'ESPAÇOS LIVRES DE ESTAR'), ('FESTAS E EVENTOS', 'FESTAS E EVENTOS'), ('PAISAGISMO', 'PAISAGISMO'), ('FINALIDADE COMERCIAL', 'FINALIDADE COMERCIAL'), ('INFRAESTRUTURA URBANA', 'INFRAESTRUTURA URBANA')], max_length=50),
        ),
    ]
